#ifndef __CCD_DEVICE_H__
#define __CCD_DEVICE_H__

#ifdef __cplusplus
extern "C" {
#endif



typedef  unsigned char  uint8;

#define CONFIG_UART_FRAME_HEAD_LENTH  1
#define CONFIG_UART_FRAME_LONG_LENTH  4


typedef enum{

 UART2WIFICOMMANDS_READ_QOS_REQUEST	= 0x05,
 UART2WIFICOMMANDS_READ_QOS_RESPONSE	= 0x05,

 UART2WIFICOMMANDS_READ_DEVICEMAC_REQUEST	=0x06,
 UART2WIFICOMMANDS_READ_DEVICEMAC_RESPONSE	=0x06,

 UART2WIFICOMMANDS_READ_DEVICESN_REQUEST	=	0x07,
 UART2WIFICOMMANDS_READ_DEVICESN_RESPONSE	=0x07,

 UART2WIFICOMMANDS_READ_DEVICEINFO_REQUEST	=0x08,
 UART2WIFICOMMANDS_READ_DEVICEINFO_RESPONSE=	0x08,

 UART2WIFICOMMANDS_WRITE_DEVICESN_REQUEST	=0x11,
 UART2WIFICOMMANDS_WRITE_DEVICESN_RESPONSE=	0x11,

 UART2WIFICOMMANDS_CHECK_NETWORK_STATE_REQUEST	=0x40,
 UART2WIFICOMMANDS_CHECK_NETWORK_STATE_RESPONSEE	=0x40,

 UART2WIFICOMMANDS_SYNC_SYSTEMTIME_REQUEST	=0x41,
 UART2WIFICOMMANDS_SYNC_SYSTEMTIME_RESPONSE	=0x41,


 UART2WIFICOMMANDS_READ_WIFIMODULE_PROPERTY_REQUEST	=0x50,
 UART2WIFICOMMANDS_READ_WIFIMODULE_PROPERTY_RESPONSE	=0x50,

 UART2WIFICOMMANDS_QUERY_DEVICE_VERSION_REQUEST	=0x61,
 UART2WIFICOMMANDS_QUERY_DEVICE_VERSION_RESPONSE	=0x61,

 UART2WIFICOMMANDS_QUERY_DEVICE_UPDATE_REQUEST	=0x62,
 UART2WIFICOMMANDS_QUERY_DEVICE_UPDATE_RESPONSE	=0x62,

 UART2WIFICOMMANDS_PUSH_DEVICE_UPDATE_REQUEST	=0x63,
 UART2WIFICOMMANDS_PUSH_DEVICE_UPDATE_RESPONSE	=0x63,

 UART2WIFICOMMANDS_ACTIVE_DEVICE_UPDATE_RESPONSE	=0x65,

 UART2WIFICOMMANDS_SET_UART_BAUD_REQUEST 	=0x66,
 UART2WIFICOMMANDS_SET_UART_BAUD_RESPONSE 	=0x66,


 UART2WIFICOMMANDS_CONFIG_WIFI_REQUEST 	=0x67,
 UART2WIFICOMMANDS_CONFIG_WIFI_RESPONSE 	=0x67,


 UART2WIFICOMMANDS_WIFI_POWER_REQUEST	=0x68,
 UART2WIFICOMMANDS_WIFI_POWER_RESPONSE	=0x68,


 UART2WIFICOMMANDS_RENAME_WIFISSID_REQUEST	=0x70,
 UART2WIFICOMMANDS_RENAME_WIFISSID_RESPONSE	=0x70,


 UART2WIFICOMMANDS_EASY_LINK_REQUEST		=0x72,
 UART2WIFICOMMANDA_LINK_RESULT_RESPONSE	=0x72,

 UART2WIFICOMMANDS_REBOOT_REQUEST	=0x82,
 UART2WIFICOMMANDS_REBOOT_RESPONSE	=0x82,

 UART2WIFICOMMANDS_RESET2FACTORY_REQUEST		=0x83,
 UART2WIFICOMMANDS_RESET2FACTORY_RESPONSE	=0x83,

 UART2WIFICOMMANDS_QUERY_DEVICE_STATUS_REQUEST	=0x21,
 UART2WIFICOMMANDS_QUERY_DEVICE_STATUS_RESPONSE =0x21,

}CCD_UART_MSG_TYPE;


#ifdef __cplusplus
}
#endif

#endif 

